spring:
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core: debug
      mongodb:
        driver:
          protocol:
            command: debug
